from src.agents.architect import get_architect_agent  # type: ignore[import-not-found]
from src.agents.functional_analyst import (  # type: ignore[import-not-found]
    get_functional_analyst_agent,  # type: ignore[import-not-found]
)
from src.agents.planner import get_planner_agent  # type: ignore[import-not-found]
from src.agents.product_owner import (  # type: ignore[import-not-found]
    get_product_owner_agent,  # type: ignore[import-not-found]
)
from workflows.epic_to_issues.envelopes import (  # type: ignore[import-not-found]
    ArchitecturalDesignEnvelope,
    BacklogEnvelope,
    FunctionalRequirementsEnvelope,
    ProductAnalysisEnvelope,
)

from apf_core.assert_gates import run_shell_command
from apf_core.workflow import ApfWorkflow


def run(epic_description: str, domain_context: str, milestone_id: str = "") -> None:
    """
    Executes the Product Management workflow: Epic Ideation -> Product Analysis -> Functional Specs -> Architectural Design -> Atomic Issue Generation.
    """
    workflow = ApfWorkflow(name="epic_to_issues")

    product_owner = get_product_owner_agent(
        domain_context,
        "Act as the Product Owner. Analyze this Epic for edge cases, validity, and define an MVP scope.",
        ProductAnalysisEnvelope,
    )

    functional_analyst = get_functional_analyst_agent(
        domain_context,
        "Act as the Functional Analyst. Translate the PO's MVP into precise system behaviors (BDD) without dictating technical architecture.",
        FunctionalRequirementsEnvelope,
    )

    architect = get_architect_agent(
        domain_context,
        "Act as the Software Architect. Take the Functional Analyst's behavioral requirements and design the physical system architecture, data models, and API contracts.",
        ArchitecturalDesignEnvelope,
    )

    scrum_master = get_planner_agent(
        domain_context,
        "Act as a Technical Scrum Master. Take the Architect's design and route it into atomic GitHub issues. Do not invent technical steps.",
        BacklogEnvelope,
    )

    # 1. PRODUCT ANALYSIS PHASE
    with workflow.lane("agent"):
        print("Running Product Owner Analysis...")
        po_envelope = workflow.run_agent(
            product_owner, f"Epic Request: {epic_description}"
        )

    # 2. FUNCTIONAL ANALYSIS PHASE
    with workflow.lane("agent"):
        print("Running Functional Analyst Translation...")
        fa_task = f"""
        [ORIGINAL EPIC]
        {epic_description}
        
        [MVP SCOPE FROM PO]
        {po_envelope.recommended_mvp_scope}
        
        [IDENTIFIED EDGE CASES]
        {", ".join(po_envelope.edge_cases)}
        
        Translate these business constraints into functional system behaviors.
        """
        fa_envelope = workflow.run_agent(functional_analyst, fa_task)

    # 3. ARCHITECTURAL DESIGN PHASE
    with workflow.lane("agent"):
        print("Running Architectural Design...")
        arch_task = f"""
        [ORIGINAL EPIC]
        {epic_description}
        
        [FUNCTIONAL BEHAVIORS TO IMPLEMENT]
        User Flows: {", ".join(fa_envelope.user_flows)}
        Error States: {", ".join(fa_envelope.error_states)}
        Acceptance Criteria: {", ".join(fa_envelope.acceptance_criteria)}
        
        Design the technical architecture. IMPORTANT: You MUST use the `save_artifact` tool to save the formal RFC document to disk (e.g., in `docs/rfcs/`). Do NOT include the full RFC text in your final response summary.
        """
        arch_envelope: ArchitecturalDesignEnvelope = workflow.run_agent(
            architect, arch_task, skills=["spec_driven"]
        )

    # 4. BREAKDOWN PHASE (Scrum Master)
    with workflow.lane("agent"):
        print("Running Scrum Master Breakdown...")
        sm_task = f"""
        [ARCHITECTURAL DESIGN & MODULES TO BUILD]
        {", ".join(arch_envelope.implementation_breakdown)}
        
        [RFC POINTER]
        {arch_envelope.rfc_path}
        
        Route these architectural modules into atomic GitHub Issues.
        """
        backlog_envelope: BacklogEnvelope = workflow.run_agent(
            scrum_master, sm_task, skills=["epic_breakdown"]
        )

    # 5. EXECUTION PHASE (GitHub API Injection)
    with workflow.lane("code"):
        # The RFC is already saved to disk by the Architect agent using save_artifact
        print(f"RFC should be available at {arch_envelope.rfc_path}")

        # Git commit the RFC before creating issues
        run_shell_command(f"git add {arch_envelope.rfc_path}")
        run_shell_command(
            f'git commit -m "docs: add RFC for {backlog_envelope.epic_title}"'
        )

        # Handle GitHub Milestone
        repo_name = ""
        if milestone_id:
            # We already have a milestone created by the human
            print(f"Using existing Milestone ID: {milestone_id}")
            milestone_number = milestone_id

            # Optional: Rename the milestone to the epic title generated by the AI
            _, repo_name_raw, _ = run_shell_command(
                "gh repo view --json nameWithOwner --jq .nameWithOwner"
            )
            repo_name = repo_name_raw.strip() if repo_name_raw else ""
            if repo_name:
                run_shell_command(
                    f'gh api -X PATCH repos/{repo_name}/milestones/{milestone_id} -f title="[Epic] {backlog_envelope.epic_title}"'
                )
        else:
            # Create a new milestone if running standalone
            print(f"Creating Milestone '{backlog_envelope.epic_title}' in GitHub...")
            _, repo_name_raw, _ = run_shell_command(
                "gh repo view --json nameWithOwner --jq .nameWithOwner"
            )
            repo_name = repo_name_raw.strip() if repo_name_raw else ""
            if repo_name:
                _milestone_ok, milestone_number_raw, _milestone_err = run_shell_command(
                    f'gh api repos/{repo_name}/milestones -f title="[Epic] {backlog_envelope.epic_title}" --jq ".number"'
                )
                milestone_number = (
                    milestone_number_raw.strip() if milestone_number_raw else ""
                )
            else:
                milestone_number = ""

        milestone_flag = f'--milestone "{milestone_number}"' if milestone_number else ""

        print(f"Creating {len(backlog_envelope.issues)} issues in GitHub...")
        success_count = 0
        for issue in backlog_envelope.issues:
            # Construct the gh cli command
            # Note: We save the body to a temp file to avoid bash escaping issues
            import tempfile

            markdown_body = f"""### 📚 Context & Architecture
Please read the Technical Specification in `{issue.rfc_pointer}` for context and logic before executing this ticket.

### 🛠️ Execution Task
{chr(10).join(f"- {step}" for step in issue.execution_task)}

### ✅ Definition of Done
{chr(10).join(f"- [ ] {dod}" for dod in issue.definition_of_done)}

### 🧪 Verification Commands
```bash
{issue.verification_command}
```
"""

            with tempfile.NamedTemporaryFile("w", delete=False, suffix=".md") as f:
                f.write(markdown_body)
                temp_path = f.name

            # Create labels gracefully if they don't exist
            all_labels = [
                issue.lifecycle_label,
                issue.size_label,
                issue.scope_label,
            ] + issue.thematic_labels
            for label in all_labels:
                # We ignore the error if it already exists
                run_shell_command(f'gh label create "{label}"')

            labels_flag = ",".join(all_labels)
            issue_title = f"{issue.issue_type}: {issue.title}"

            # Fire the command
            ok, _stdout, stderr = run_shell_command(
                f'gh issue create --title "{issue_title}" --body-file "{temp_path}" --label "{labels_flag}" {milestone_flag}'
            )

            # Clean up

            os.remove(temp_path)

            if ok:
                success_count += 1
                print(f"Created issue: {issue.title}")
            else:
                print(f"Failed to create issue '{issue.title}': {stderr}")

        if success_count == len(backlog_envelope.issues):
            print("Successfully populated the backlog.")
        else:
            print("Warning: Some issues failed to create.")

    # 5. HALT
    with workflow.lane("engineer"):
        print(
            "Epic breakdown complete. Check your GitHub project board for the new apf:backlog issues."
        )


if __name__ == "__main__":
    # Example execution
    run(
        epic_description="We need a new user authentication system that supports magic links via email and JWT tokens. It must be highly secure.",
        domain_context="You are in a FastAPI software engineering repository with a PostgreSQL database.",
    )
